### ISSUE TITLE
Uploads folder

### ISSUE THREAD

**Issue by mdumouchel** [cmrust/hapi-dropzone#1]
Hey Thanks for the example.  Btw might want to add in the documentation to create the upload folder.  Also might be kind of a interesting module/plugin to abstract the code to expose a handler so you just tell where to put the file.  Just idea and again thanks for the example was having some issues getting this working.

**Comment by cmrust** [comment]
@mdumouchel Thanks for the comments and sorry for the slow response. I've made the changes you've suggested in this latest [commit](https://github.com/cmrust/hapi-dropzone/commit/d1718aa29270ac3678b0a836ef4344a482780178).
